name: Upload Changed Networks

on:
  push:
    branches:
      - add-save-network-api-key

jobs:
  upload_changed_networks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: add-save-network-api-key

      - name: Upload changed jsons
        id: upload_changed_jsons
        env:
          SAVE_NETWORK_API_KEY: ${{ secrets.SAVE_NETWORK_API_KEY }}
        run: |
          echo "----$SAVE_NETWORK_API_KEY"
          echo "1111${{ secrets.SAVE_NETWORK_API_KEY }}"
          
          
          # Use git to get the list of changed files
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Initialize an empty array to store the changed network jsons
          changed_jsons=()
  
          # Loop through the changed files to fetch the content
          for file in $changed_files; do
            # Use the file command to check the MIME type
            mime_type=$(file -b --mime-type "$file")
  
            # Check if the MIME type is JSON
            if [[ ! "$mime_type" == "application/json" ]]; then
              continue
            fi
          
            # Read the content of the file
            file_content=$(cat "$file")
          
            # Parse the JSON data
            parsed_json=$(echo "$file_content" | jq -c .)
          
            # Make an API post request with the extracted json
            curl -X POST \
              -H "Content-type: application/json" \
              -H "Authorization: Bearer $SAVE_NETWORK_API_KEY" \
              -d "$parsed_json" \
              "https://savenetworkrequest-zbrmx4rjia-uc.a.run.app"
          done
